Repository MobiFlight/MobiFlight-Connector, pull requests merged in 2022-05, with the labels that each got.

#773 Update to Beta Firmware 2.1.2
  Boards/arduino_mega.board.json
  Boards/arduino_micro.board.json
  Boards/arduino_uno.board.json
  MobiFlight/MobiFlightModule.cs
  MobiFlightConnector.csproj
  firmware/mobiflight_mega_2_1_1.hex
  firmware/mobiflight_mega_2_1_2.hex
  firmware/mobiflight_micro_2_1_1.hex
  firmware/mobiflight_micro_2_1_2.hex
  firmware/mobiflight_uno_2_1_1.hex
  firmware/mobiflight_uno_2_1_2.hex
Labels: firmware

#786 Comma or Semicolon in LCD display are displayed properly
  MobiFlight/MobiFlightLcdDisplay.cs
Labels: bug, firmware, connector

#788 Added message to inform that the MSFS2020 key events don't work
  UI/Panels/Action/KeyboardInputPanel.Designer.cs
  UI/Panels/Action/KeyboardInputPanel.de.resx
  UI/Panels/Action/KeyboardInputPanel.resx
Labels: enhancement, UI

#789 "No Output Device configured" Message redirects to board settings
  UI/Dialogs/ConfigWizard.cs
  UI/Dialogs/InputConfigWizard.Designer.cs
  UI/Dialogs/InputConfigWizard.cs
  UI/Dialogs/InputConfigWizard.resx
  UI/Panels/OutputWizard/DisplayPanel.cs
Labels: enhancement, UI

#792 Fixed missing row select on right click
  UI/Panels/InputConfigPanel.cs
Labels: bug, UI

#794 Independant update routine for the input preconditions
  MobiFlight/ExecutionManager.cs
Labels: enhancement, UI

#796 9.3.2.2 Beta Prep Tasks
  Boards/arduino_mega.board.json
  Boards/arduino_micro.board.json
  Boards/arduino_uno.board.json
  MobiFlightConnector.csproj
  Presets/msfs2020_hubhop_presets.json
  Properties/AssemblyInfo.cs
  firmware/mobiflight_mega_2_1_2.hex
  firmware/mobiflight_mega_2_1_3.hex
  firmware/mobiflight_micro_2_1_2.hex
  firmware/mobiflight_micro_2_1_3.hex
  firmware/mobiflight_uno_2_1_2.hex
  firmware/mobiflight_uno_2_1_3.hex
Labels: development

#798 Fixed analog input save problem
  MobiFlight/InputConfigItem.cs
  MobiFlightUnitTests/MobiFlight/InputConfigItemTests.cs
Labels: bug_beta

#815 Update to firmware version 2.2.0 Stable
  Boards/arduino_mega.board.json
  Boards/arduino_micro.board.json
  Boards/arduino_uno.board.json
  MobiFlightConnector.csproj
  firmware/mobiflight_mega_2_1_3.hex
  firmware/mobiflight_mega_2_2_0.hex
  firmware/mobiflight_micro_2_1_3.hex
  firmware/mobiflight_micro_2_2_0.hex
  firmware/mobiflight_uno_2_1_3.hex
  firmware/mobiflight_uno_2_2_0.hex
Labels: enhancement, firmware

#816 Add brightness reference value range explanation
  UI/Panels/Output/DisplayLedDisplayPanel.Designer.cs
  UI/Panels/Output/DisplayLedDisplayPanel.de.resx
  UI/Panels/Output/DisplayLedDisplayPanel.resx
Labels: enhancement, UI
