Repository MobiFlight/MobiFlight-Connector, pull requests merged in 2022-06, with the labels that each got.

#832 Changed version to 9.4.0.2
  Properties/AssemblyInfo.cs
Labels: development, ignore-for-release

#834 Fix problem with exception for interpolation (9.4.0.2)
  MobiFlightUnitTests/MobiFlight/OutputConfigItemTests.cs
  MobiFlightUnitTests/MobiFlightUnitTests.csproj
  MobiFlightUnitTests/assets/MobiFlight/OutputConfig/OutputConfigItem/ReadXmlTest.Interpolation.xml
  UI/Panels/Config/InterpolationPanel.Designer.cs
  UI/Panels/Config/InterpolationPanel.cs
  UI/Panels/Config/InterpolationPanel.resx
Labels: bug_beta, ignore-for-release-notes

#836 Updated Solution to NET4.8
  CmdMessenger/CmdMessenger/CSharp/CommandMessenger/CommandMessenger.csproj
  VersionInfo/App.config
  VersionInfo/VersionInfo.csproj
Labels: development

#837 Check for null and make UpdateFrequency a property
  xplane/XplaneCache.cs
Labels: development, ignore-for-release-notes

#838 Updated version to 9.4.0.3
  Properties/AssemblyInfo.cs
Labels: development, ignore-for-release-notes

#841 Add 3rd party license information in about dialog
  MobiFlightConnector.csproj
  UI/Dialogs/AboutForm.Designer.cs
  UI/Dialogs/AboutForm.cs
  UI/Dialogs/AboutForm.de.resx
  UI/Dialogs/AboutForm.resx
  UI/Panels/About/LicenseReferenceControl.Designer.cs
  UI/Panels/About/LicenseReferenceControl.cs
  UI/Panels/About/LicenseReferenceControl.resx
Labels: enhancement, UI

#843 Fix slow loading of config
  Base/AppTelemetry.cs
Labels: bug

#844 Poll Speed affects xplane update frequency
  MobiFlight/ExecutionManager.cs
  UI/MainForm.cs
  xplane/XplaneCache.cs
Labels: ignore-for-release-notes

#846 Ignore COM ports selected by user
  MobiFlight/MobiFlightCache.cs
  MobiFlightConnector.csproj
  ProjectMessages/ProjectMessages.Designer.cs
  ProjectMessages/ProjectMessages.de.resx
  ProjectMessages/ProjectMessages.resx
  Properties/Resources.Designer.cs
  Properties/Resources.resx
  Properties/Settings.Designer.cs
  Properties/Settings.settings
  Resources/port-deactivated.png
  UI/Panels/Settings/MobiFlightPanel.Designer.cs
  UI/Panels/Settings/MobiFlightPanel.cs
  UI/Panels/Settings/MobiFlightPanel.de.resx
  UI/Panels/Settings/MobiFlightPanel.resx
  app.config
Labels: UI

#851 Shift Register Names are not displayed on the mappings screen #850
  UI/Panels/OutputConfigPanel.cs
Labels: bug

#853 Fixed problem with InputAction and Config Ref
  MobiFlight/OutputConfigItem.cs
Labels: ignore-for-release-notes

#859 Use tag for release version
  .github/workflows/publish.yml
Labels: development
