Repository MobiFlight/MobiFlight-Connector, pull requests merged in 2023-01, with the labels that each got.

#1066 Fixing reported bugs and improvements
  MobiFlight/ExecutionManager.cs
  MobiFlight/MobiFlightLedModule.cs
  MobiFlight/Modifier/Comparison.cs
  MobiFlightUnitTests/MobiFlight/MobiFlightLedModuleTests.cs
Labels: bug, bug_beta

#1083 Update check happens first thing after startup
  UI/MainForm.cs
Labels: enhancement

#1087 Update MSFS2020 & XPlane HubHop presets
  ProjectMessages/ProjectMessages.Designer.cs
  ProjectMessages/ProjectMessages.de.resx
  ProjectMessages/ProjectMessages.resx
  SimConnectMSFS/WasmModuleUpdater.cs
  UI/MainForm.Designer.cs
  UI/MainForm.cs
  UI/MainForm.resx
Labels: feature

#1096 Solution for Input action panel problems reported for 9.6.0.5
  UI/Dialogs/InputConfigWizard.cs
  UI/Panels/OutputWizard/DisplayPanel.cs
Labels: bug, bug_beta

#1098 Auto-home setting is correctly saved
  MobiFlight/Config/Stepper.cs
  UI/Panels/Device/MFStepperPanel.Designer.cs
  UI/Panels/Device/MFStepperPanel.cs
Labels: bug, bug_beta
