Repository MobiFlight/MobiFlight-Connector, pull requests merged in 2023-11, with the labels that each got.

#1364 Dynamic board detection
  Arcaze/ArcazeCache.cs
  Boards/arduino_micro.board.json
  Boards/raspberrypi_pico.board.json
  MobiFlight/ExecutionManager.cs
  MobiFlight/MobiFlightCache.cs
  MobiFlight/MobiFlightCacheInterface.cs
  MobiFlight/MobiFlightFirmwareUpdater.cs
  MobiFlight/MobiFlightLedModule.cs
  MobiFlight/MobiFlightModule.cs
  MobiFlight/MobiFlightModuleInfo.cs
  MobiFlight/Monitors/DeviceMonitor.cs
  MobiFlight/Monitors/SerialPortMonitor.cs
  MobiFlight/Monitors/UsbDeviceMonitor.cs
  MobiFlight/PortDetails.cs
  MobiFlightConnector.csproj
  MobiFlightUnitTests/MobiFlight/MobiFlightModuleInfoTests.cs
  MobiFlightUnitTests/MobiFlight/MobiFlightModuleTests.cs
  MobiFlightUnitTests/MobiFlightUnitTests.csproj
  ProjectMessages/ProjectMessages.Designer.cs
  ProjectMessages/ProjectMessages.de.resx
  ProjectMessages/ProjectMessages.resx
  Properties/Resources.Designer.cs
  Properties/Resources.resx
  Resources/module-arduino.png
  Resources/module-changed.png
  Resources/module-mobiflight-update.png
  Resources/module-mobiflight.png
  Resources/module-pico.png
  UI/Dialogs/SettingsDialog.cs
  UI/Forms/FirmwareUpdateProcess.cs
  UI/MainForm.cs
  UI/Panels/Device/MFModulePanel.Designer.cs
  UI/Panels/Device/MFModulePanel.cs
  UI/Panels/Device/MFModulePanel.resx
  UI/Panels/Settings/MobiFlightPanel.Designer.cs
  UI/Panels/Settings/MobiFlightPanel.cs
  UI/Panels/Settings/MobiFlightPanel.de.resx
  UI/Panels/Settings/MobiFlightPanel.resx
Labels: enhancement

#1375 Centralize OnLongRelease Logic
  MobiFlight/InputConfig/ButtonInputConfig.cs
  MobiFlight/InputConfigItem.cs
Labels: code-cleansing, ignore-for-release-notes

#1378 Use mono-space in code text fields
  UI/Panels/Config/HubHopPresetPanel.Designer.cs
  UI/Panels/Modifier/ComparisonModifierPanel.Designer.cs
  UI/Panels/Modifier/TransformModifierPanel.Designer.cs
Labels: enhancement

#1383 Added configurable long button release and on hold with repeat
  MobiFlight/InputConfig/ButtonInputConfig.cs
  MobiFlight/MobiFlightButton.cs
  MobiFlight/MobiFlightModule.cs
  MobiFlightConnector.csproj
  MobiFlightUnitTests/MobiFlight/InputConfig/ButtonInputConfigTests.cs
  MobiFlightUnitTests/assets/MobiFlight/InputConfig/ButtonInputConfig/ReadXmlTest.1.xml
  MobiFlightUnitTests/assets/MobiFlight/InputConfig/ButtonInputConfig/WriteXmlTest.1.xml
  ProjectMessages/ProjectMessages.Designer.cs
  ProjectMessages/ProjectMessages.de.resx
  ProjectMessages/ProjectMessages.resx
  UI/Dialogs/InputConfigWizard.cs
  UI/Panels/Action/EventIdInputPanel.cs
  UI/Panels/Action/JeehellInputPanel.cs
  UI/Panels/Action/KeyboardInputPanel.cs
  UI/Panels/Action/LuaMacroInputPanel.cs
  UI/Panels/Action/MSFS2020CustomInputPanel.cs
  UI/Panels/Action/PmdgEventIdInputPanel.cs
  UI/Panels/Action/RetriggerInputPanel.cs
  UI/Panels/Action/VJoyInputPanel.cs
  UI/Panels/Action/VariableInputPanel.cs
  UI/Panels/Action/XplaneInputPanel.cs
  UI/Panels/Config/FsuipcConfigPanel.cs
  UI/Panels/Config/IPanelConfigSync.cs
  UI/Panels/Config/InputActionMapping.cs
  UI/Panels/Input/ButtonPanel.Designer.cs
  UI/Panels/Input/ButtonPanel.cs
  UI/Panels/Input/InputMultiplexerPanel.Designer.cs
  UI/Panels/Input/InputMultiplexerPanel.cs
  UI/Panels/Input/InputMultiplexerPanel.resx
  UI/Panels/Input/InputShiftRegisterPanel.Designer.cs
  UI/Panels/Input/InputShiftRegisterPanel.cs
  UI/Panels/Input/InputShiftRegisterPanel.resx
Labels: feature

#1388 Clean up code style warnings
  MobiFlight/ExecutionManager.cs
  MobiFlight/MobiFlightCache.cs
  UI/Dialogs/ConfigWizard.cs
  UI/Dialogs/InputConfigWizard.cs
  UI/MainForm.cs
  UI/Panels/OutputWizard/DisplayPanel.cs
  UI/Panels/Settings/MobiFlightPanel.cs
Labels: development

#1389 Automatically keep boards alive when Run is active
  MobiFlight/ExecutionManager.cs
  MobiFlight/MobiFlightCache.cs
  MobiFlight/MobiFlightModule.cs
Labels: bug

#1407 Code cleanup
  MobiFlight/ExecutionManager.cs
Labels: development

#1413 Transformation modifier works with String type
  MobiFlight/Modifier/FsuipcStringModifierList.cs
  MobiFlight/Modifier/ModifierList.cs
  MobiFlight/Modifier/Transformation.cs
  MobiFlight/OutputConfigItem.cs
  MobiFlightConnector.csproj
  MobiFlightUnitTests/MobiFlight/Modifier/TransformationTests.cs
  MobiFlightUnitTests/MobiFlight/OutputConfigItemTests.cs
  MobiFlightUnitTests/assets/Base/ConfigFile/7.5.0-7.5.1-upgrade.mcc.exp
  MobiFlightUnitTests/assets/Base/ConfigFile/OpenFileTest.2912.xml.exp
  MobiFlightUnitTests/assets/Base/ConfigFile/OpenFileTest.xml.exp
  MobiFlightUnitTests/assets/Base/ConfigFile/example-default-plane-v6.1.mcc.exp
  MobiFlightUnitTests/assets/Base/ConfigFile/example-jeehell-datapipe.mcc.exp
  MobiFlightUnitTests/assets/MobiFlight/OutputConfig/OutputConfigItem/WriteXmlTest.1.xml
  MobiFlightUnitTests/assets/MobiFlight/Transformation/WriteXmlTest.1.xml
Labels: bug_beta

#1426 Perform installation when zip file already available
  MobiFlight-Installer/MobiFlight-Installer/Properties/AssemblyInfo.cs
  MobiFlight-Installer/MobiFlight-Installer/UI/UpdaterMainForm.cs
Labels: bug

#1432 Improve readibility of interpolation modifier settings
  UI/Panels/Modifier/InterpolationModifier/InterpolationMappingPanel.Designer.cs
  UI/Panels/Modifier/InterpolationModifierPanel.cs
Labels: beta, ignore-for-release-notes

#1418 Drag'nDrop improvements including reset sorting
  ProjectMessages/ProjectMessages.Designer.cs
  ProjectMessages/ProjectMessages.de.resx
  ProjectMessages/ProjectMessages.resx
  UI/MainForm.cs
  UI/Panels/InputConfigPanel.Designer.cs
  UI/Panels/InputConfigPanel.cs
  UI/Panels/InputConfigPanel.resx
  UI/Panels/OutputConfigPanel.Designer.cs
  UI/Panels/OutputConfigPanel.cs
Labels: feature

#1438 Startup will finish with only one pico
  MobiFlight/MobiFlightCache.cs
Labels: bug_beta

#1451 InputShifters save OnHold and OnLongRelease correctly
  MobiFlight/InputConfig/ButtonInputConfig.cs
  MobiFlight/InputConfig/InputMultiplexerConfig.cs
  MobiFlight/InputConfig/InputShiftRegisterConfig.cs
  MobiFlightUnitTests/MobiFlight/InputConfig/ButtonInputConfigTests.cs
  MobiFlightUnitTests/MobiFlight/InputConfig/InputMultiplexerConfigTests.cs
  MobiFlightUnitTests/MobiFlight/InputConfig/InputShiftRegisterConfigTests.cs
  MobiFlightUnitTests/assets/MobiFlight/InputConfig/ButtonInputConfig/WriteXmlTest.1.xml
  MobiFlightUnitTests/assets/MobiFlight/InputConfig/InputMultiplexerConfig/WriteXmlTest.1.xml
  MobiFlightUnitTests/assets/MobiFlight/InputConfig/InputShiftRegisterConfig/WriteXmlTest.1.xml
Labels: bug_beta
