Repository MobiFlight/MobiFlight-Connector, pull requests merged in 2023-12, with the labels that each got.

#1474 remove MobiFlight-Admin from ignore section
  .github/release.yml
Labels: ignore-for-release-notes

#1496 Interpolation supports float values
  UI/Dialogs/ConfigWizard.cs
  UI/Panels/Modifier/InterpolationModifier/InterpolationMappingPanel.cs
Labels: bug, hotfix

#1454 Pico - Limit the number of PWM pins to 16
  Boards/raspberrypi_pico.board.json
Labels: bug

#1495 Resolve crash with custom device statistics
  MobiFlight/MobiFlightModule.cs
Labels: ready-to-merge

#1497 Add row description to config window titles
  UI/Dialogs/ConfigWizard.cs
  UI/Dialogs/InputConfigWizard.cs
  UI/Panels/InputConfigPanel.cs
  UI/Panels/OutputConfigPanel.cs
Labels: enhancement

#1503 All boards - Increase max number of devices for all types
  Boards/arduino_mega.board.json
  Boards/arduino_micro.board.json
  Boards/arduino_nano.board.json
  Boards/arduino_uno.board.json
  Boards/kav_mega.board.json.inactive
  Boards/mobiflight_genericI2C_mega.board.json.inactive
  Boards/raspberrypi_pico.board.json
Labels: enhancement

#1507 UI: Custom Board & Community integration
  Base/Extensions.cs
  Boards/board-logo.png
  Boards/mfboard.schema.json
  Community/MobiFlight/boards/board-logo.png
  Community/MobiFlight/boards/mobiflight_GNC255_mega.board.json
  Community/MobiFlight/boards/mobiflight_GNC255_pico.board.json
  Community/MobiFlight/boards/mobiflight_genericI2C_mega.board.json
  Community/MobiFlight/boards/mobiflight_genericI2C_raspberry_pico.board.json
  Community/MobiFlight/devices/mobiflight.genericI2C.device.json
  Community/MobiFlight/devices/mobiflight.gnc255.device.json
  Community/MobiFlight/firmware/mobiflight_genericI2C_mega_2_5_0.hex
  Community/MobiFlight/firmware/mobiflight_genericI2C_raspberrypico_2_5_0.uf2
  Community/MobiFlight/firmware/mobiflight_gnc255_mega_2_5_0.hex
  Community/MobiFlight/firmware/mobiflight_gnc255_raspberrypico_2_5_0.uf2
  Community/MobiFlight/firmware/reset.arduino_mega_1_0_2.hex
  Community/MobiFlight/firmware/reset.raspberry_pico_flash_nuke.uf2
  Community/kavSimulations/boards/board-logo.png
  Community/kavSimulations/boards/kav_mega.board.json
  Community/kavSimulations/boards/kav_pico.board.json
  Community/kavSimulations/config/MF_FBWA320_1FCU_2EFIS_Config_new.mcc
  Community/kavSimulations/devices/kav_battery.device.json
  Community/kavSimulations/devices/kav_efis.device.json
  Community/kavSimulations/devices/kav_fcu.device.json
  Community/kavSimulations/devices/kav_rad_tcas.device.json
  Community/kavSimulations/devices/kav_rudder.device.json
  Community/kavSimulations/firmware/kav_mega_2_5_0.hex
  Community/kavSimulations/firmware/reset.arduino_mega_1_0_2.hex
  Community/kavSimulations/logo.png
  Community/miniCOCKPIT/boards/board-logo.png
  Community/miniCOCKPIT/boards/miniCOCKPIT_miniFCU_mega.board.json
  Community/miniCOCKPIT/config/miniCOCKPIT_miniFCU_mega.mfmc
  Community/miniCOCKPIT/devices/miniCOCKPIT_miniFCU_mega.device.json
  Community/miniCOCKPIT/firmware/miniCOCKPIT_miniFCU_mega_0_9_1.hex
  Community/miniCOCKPIT/firmware/reset.miniFCU.ino.hex
  Community/miniCOCKPIT/logo.png
  Community/miniCOCKPIT/profiles/msfs2020/FBW-a320.mcc
  MobiFlight/Board.cs
  MobiFlight/BoardDefinitions.cs
  MobiFlight/CustomDevices/CustomDevice.cs
  MobiFlight/CustomDevices/CustomDeviceDefinitions.cs
  MobiFlight/Joysticks/JoystickManager.cs
  MobiFlight/JsonBackedObject.cs
  MobiFlight/MidiBoard/MidiBoardManager.cs
  MobiFlightConnector.csproj
  MobiFlightUnitTests/MobiFlight/JsonDefinitionFilesTests.cs
  UI/Forms/FirmwareUpdateProcess.cs
  UI/Panels/Device/MFModulePanel.Designer.cs
  UI/Panels/Device/MFModulePanel.ar-LY.resx
  UI/Panels/Device/MFModulePanel.cs
  UI/Panels/Device/MFModulePanel.de.resx
  UI/Panels/Device/MFModulePanel.resx
  UI/Panels/Settings/MobiFlightPanel.cs
  firmware/cmd_test_mega/cmd_test_mega.ino
Labels: feature

#1528 Update miniFCU firmware to 0.9.2
  Community/miniCOCKPIT/boards/miniCOCKPIT_miniFCU_mega.board.json
  Community/miniCOCKPIT/firmware/miniCOCKPIT_miniFCU_mega_0_9_1.hex
  Community/miniCOCKPIT/firmware/miniCOCKPIT_miniFCU_mega_0_9_2.hex
Labels: enhancement

#1535 Save Lua-Macro value correctly
  MobiFlight/InputConfig/LuaMacroInputAction.cs
  MobiFlightUnitTests/MobiFlight/InputConfig/LuaMacroInputActionTests.cs
Labels: bug
